### ISSUE TITLE
When Second learning time, this error is comming

### ISSUE THREAD

**Issue by proauto** [siyuanzhao/2016-EDM#1]
1. first run
   tensorflow/core/framework/op_kernel.cc:940] Invalid argument: indices[1635] = [1635,230] is out of bounds: need 0 <= index < [4818,222]
2. second run
   tensorflow/core/framework/op_kernel.cc:940] Invalid argument: indices[1] = [1,231] is out of bounds: need 0 <= index < [4818,222]

I wonder why this situation is made. 

Something wrong in input tensor size

Size of the input is changed randomly,(1635, 1)

Please check about this issue.

**Comment by siyuanzhao** [comment]
The latest check-in should fix this bug. I also updated readme.
The cause of the bug:
The number of skill is previously manually set in the code. The number of skills in previous code is actually smaller than the number of skills in the data set.
