### ISSUE TITLE
What is the difference between Data (b) & (c)

### ISSUE THREAD

**Issue by proauto** [siyuanzhao/2016-EDM#2]
I wonder what is the difference between Data 09-10 (b) & (c).

In paper, Repeat and Combine is difference.

But when I see the table, I can't find the that meaning.

If the problem's skill is combine of 128 & 140.
I understand (b) case
input is such like 

128 140
1 1

I think it is repeat sequence.

And what's the difference 09-10(c) ???

Please help self-studying student...

**Comment by siyuanzhao** [comment]
In data c, we combine two skills into a new skill.
Let's say there are 140 skills in total in the dataset before any combination.
We will combine 128 and 140 and have a new skill 141. 
The new data would look like the following:
128 140     =>   141 
1 1                       1

Let me know if you have any other questions. I'm glad I could help you.
The work in our lab mainly focuses on Intelligent Tutor Systems and student modeling.

**Comment by proauto** [comment]
Oh it is simple!
Thank you for your nice answer.
