### ISSUE TITLE
这里只有DKT的实现，能否提供一下PFA的实现？

### ISSUE THREAD

**Issue by 28554010** [siyuanzhao/2016-EDM#5]
我看到这篇论文Table 2. An example of PFA’s training data里面列出的训练数据还有一项diffculty。我不太理解！经典的Performance Factor Analysis里面，参数beta代表知识点的难易度。但是beta不是训练输入的数据，而是逻辑回归要拟合的参数。是计算结果，不是计算前预估吧？你文章里提到的diffculty是代表什么？

**Comment by siyuanzhao** [comment]
pfa是另外一个作者Xiaolu来实现和负责
你需要去问他才能得到这些细节
